/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ssbbss.view;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import ssbbss.DBOperation.CommonDAO;
import ssbbss.DBOperation.CreateInvestmentCop;
import ssbbss.DBOperation.DBConnection;
import ssbbss.domain.CreateInvestment;

/**
 *
 * @author Md Yasin Arif
 */
public class CreateInvestmentAccountPage1 extends javax.swing.JFrame {

    private JFrame frame;

    /**
     * Creates new form LoginPage
     */
    public CreateInvestmentAccountPage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnSaveCA = new javax.swing.JButton();
        btnWF = new javax.swing.JButton();
        btnIcReset = new javax.swing.JButton();
        btnIcSearch = new javax.swing.JButton();
        btnCA = new javax.swing.JButton();
        btnSA = new javax.swing.JButton();
        btnSHA = new javax.swing.JButton();
        btnIA = new javax.swing.JButton();
        jLabelACT = new javax.swing.JLabel();
        iStartDate = new javax.swing.JTextField();
        iProjectName = new javax.swing.JTextField();
        iFatherHusbendName = new javax.swing.JTextField();
        jLabelACT5 = new javax.swing.JLabel();
        iProjectLocation = new javax.swing.JTextField();
        jLabelACT6 = new javax.swing.JLabel();
        iNID = new javax.swing.JTextField();
        jLabelACT7 = new javax.swing.JLabel();
        iPresentAddress = new javax.swing.JTextField();
        jLabelACT13 = new javax.swing.JLabel();
        iCardNo = new javax.swing.JTextField();
        jLabelACT14 = new javax.swing.JLabel();
        iInvestedAmount = new javax.swing.JTextField();
        jLabelACT15 = new javax.swing.JLabel();
        iFromNO = new javax.swing.JTextField();
        AccountType2 = new javax.swing.JComboBox<>();
        jLabelACT17 = new javax.swing.JLabel();
        jLabelACT18 = new javax.swing.JLabel();
        iPresentAddressPS = new javax.swing.JTextField();
        iPresentAddressPO = new javax.swing.JTextField();
        jLabelACT19 = new javax.swing.JLabel();
        iPresentAddressD = new javax.swing.JTextField();
        jLabelACT20 = new javax.swing.JLabel();
        iParmanetAddress = new javax.swing.JTextField();
        jLabelACT21 = new javax.swing.JLabel();
        iParmanetAddressPO = new javax.swing.JTextField();
        jLabelACT22 = new javax.swing.JLabel();
        iParmanetAddressPS = new javax.swing.JTextField();
        jLabelACT23 = new javax.swing.JLabel();
        iParmanetAddressD = new javax.swing.JTextField();
        iAccountNo = new javax.swing.JTextField();
        jLabelACT25 = new javax.swing.JLabel();
        btnWF1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        btnIcUpdate = new javax.swing.JButton();
        btnSaveCA3 = new javax.swing.JButton();
        btnSaveCA4 = new javax.swing.JButton();
        jLabelACT10 = new javax.swing.JLabel();
        jLabelACT27 = new javax.swing.JLabel();
        iName = new javax.swing.JTextField();
        jLabelACT26 = new javax.swing.JLabel();
        iProjectDuration = new javax.swing.JTextField();
        jLabelACT28 = new javax.swing.JLabel();
        iMotherName = new javax.swing.JTextField();
        jLabelACT29 = new javax.swing.JLabel();
        iMobilNo = new javax.swing.JTextField();
        btnSaveCA5 = new javax.swing.JButton();
        btnSaveCA6 = new javax.swing.JButton();
        btnIcSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnIcExit = new javax.swing.JButton();
        btnCiSave = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnSaveCA.setBackground(new java.awt.Color(0, 102, 0));
        btnSaveCA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSaveCA.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCA.setText("Investment A/C");
        btnSaveCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCAActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveCA);
        btnSaveCA.setBounds(990, 140, 170, 30);

        btnWF.setBackground(new java.awt.Color(0, 102, 0));
        btnWF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnWF.setForeground(new java.awt.Color(255, 255, 255));
        btnWF.setText("Welfare Fund");
        btnWF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWFActionPerformed(evt);
            }
        });
        jPanel1.add(btnWF);
        btnWF.setBounds(20, 440, 230, 40);

        btnIcReset.setBackground(new java.awt.Color(0, 102, 0));
        btnIcReset.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIcReset.setForeground(new java.awt.Color(255, 255, 255));
        btnIcReset.setText("Reset");
        btnIcReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnIcReset);
        btnIcReset.setBounds(840, 630, 100, 30);

        btnIcSearch.setBackground(new java.awt.Color(0, 102, 0));
        btnIcSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIcSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnIcSearch.setText("Search");
        btnIcSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnIcSearch);
        btnIcSearch.setBounds(1050, 210, 110, 30);

        btnCA.setBackground(new java.awt.Color(0, 102, 0));
        btnCA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCA.setForeground(new java.awt.Color(255, 255, 255));
        btnCA.setText("Create Account");
        btnCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCAMouseClicked(evt);
            }
        });
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });
        jPanel1.add(btnCA);
        btnCA.setBounds(20, 200, 230, 40);

        btnSA.setBackground(new java.awt.Color(0, 102, 0));
        btnSA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSA.setForeground(new java.awt.Color(255, 255, 255));
        btnSA.setText("Saving Account");
        btnSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAActionPerformed(evt);
            }
        });
        jPanel1.add(btnSA);
        btnSA.setBounds(20, 260, 230, 40);

        btnSHA.setBackground(new java.awt.Color(0, 102, 0));
        btnSHA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSHA.setForeground(new java.awt.Color(255, 255, 255));
        btnSHA.setText("Share Account");
        btnSHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSHAActionPerformed(evt);
            }
        });
        jPanel1.add(btnSHA);
        btnSHA.setBounds(20, 320, 230, 40);

        btnIA.setBackground(new java.awt.Color(0, 102, 0));
        btnIA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIA.setForeground(new java.awt.Color(255, 255, 255));
        btnIA.setText("Investment Account");
        btnIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIAActionPerformed(evt);
            }
        });
        jPanel1.add(btnIA);
        btnIA.setBounds(20, 380, 230, 40);

        jLabelACT.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT.setText("Start Date ");
        jLabelACT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT);
        jLabelACT.setBounds(830, 250, 170, 30);

        iStartDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iStartDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iStartDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iStartDateActionPerformed(evt);
            }
        });
        jPanel1.add(iStartDate);
        iStartDate.setBounds(1010, 250, 160, 30);

        iProjectName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iProjectName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iProjectName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iProjectNameActionPerformed(evt);
            }
        });
        jPanel1.add(iProjectName);
        iProjectName.setBounds(490, 250, 330, 30);

        iFatherHusbendName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iFatherHusbendName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iFatherHusbendName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iFatherHusbendName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iFatherHusbendNameActionPerformed(evt);
            }
        });
        jPanel1.add(iFatherHusbendName);
        iFatherHusbendName.setBounds(490, 370, 330, 30);

        jLabelACT5.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT5.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT5.setText("Project Location");
        jLabelACT5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT5);
        jLabelACT5.setBounds(280, 290, 200, 30);

        iProjectLocation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iProjectLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iProjectLocation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iProjectLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iProjectLocationActionPerformed(evt);
            }
        });
        jPanel1.add(iProjectLocation);
        iProjectLocation.setBounds(490, 290, 330, 30);

        jLabelACT6.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT6.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT6.setText("NID No");
        jLabelACT6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT6);
        jLabelACT6.setBounds(830, 370, 170, 30);

        iNID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iNID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iNID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNIDActionPerformed(evt);
            }
        });
        jPanel1.add(iNID);
        iNID.setBounds(1010, 370, 160, 30);

        jLabelACT7.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT7.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT7.setText("Present Address");
        jLabelACT7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT7);
        jLabelACT7.setBounds(280, 450, 200, 30);

        iPresentAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iPresentAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iPresentAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iPresentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPresentAddressActionPerformed(evt);
            }
        });
        jPanel1.add(iPresentAddress);
        iPresentAddress.setBounds(490, 450, 330, 30);

        jLabelACT13.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT13.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT13.setText("Card No");
        jLabelACT13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT13);
        jLabelACT13.setBounds(780, 210, 100, 30);

        iCardNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iCardNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iCardNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iCardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCardNoActionPerformed(evt);
            }
        });
        jPanel1.add(iCardNo);
        iCardNo.setBounds(890, 210, 150, 30);

        jLabelACT14.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT14.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT14.setText("Invested Amount");
        jLabelACT14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT14);
        jLabelACT14.setBounds(830, 290, 170, 30);

        iInvestedAmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iInvestedAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iInvestedAmount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iInvestedAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iInvestedAmountActionPerformed(evt);
            }
        });
        jPanel1.add(iInvestedAmount);
        iInvestedAmount.setBounds(1010, 290, 160, 30);

        jLabelACT15.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT15.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT15.setText("From NO");
        jLabelACT15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT15);
        jLabelACT15.setBounds(560, 210, 100, 30);

        iFromNO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iFromNO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iFromNO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iFromNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iFromNOActionPerformed(evt);
            }
        });
        jPanel1.add(iFromNO);
        iFromNO.setBounds(670, 210, 90, 30);

        AccountType2.setBackground(new java.awt.Color(53, 255, 0));
        AccountType2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AccountType2.setForeground(new java.awt.Color(0, 153, 0));
        AccountType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Father's Name", "Husbend's Name" }));
        AccountType2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(AccountType2);
        AccountType2.setBounds(280, 370, 200, 30);

        jLabelACT17.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT17.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT17.setText("Post Office");
        jLabelACT17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT17);
        jLabelACT17.setBounds(830, 450, 170, 30);

        jLabelACT18.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT18.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT18.setText("Police Station");
        jLabelACT18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT18);
        jLabelACT18.setBounds(440, 490, 180, 30);

        iPresentAddressPS.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iPresentAddressPS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iPresentAddressPS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iPresentAddressPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPresentAddressPSActionPerformed(evt);
            }
        });
        jPanel1.add(iPresentAddressPS);
        iPresentAddressPS.setBounds(630, 490, 190, 30);

        iPresentAddressPO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iPresentAddressPO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iPresentAddressPO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iPresentAddressPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPresentAddressPOActionPerformed(evt);
            }
        });
        jPanel1.add(iPresentAddressPO);
        iPresentAddressPO.setBounds(1010, 450, 160, 30);

        jLabelACT19.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT19.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT19.setText("District");
        jLabelACT19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT19);
        jLabelACT19.setBounds(830, 490, 170, 30);

        iPresentAddressD.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iPresentAddressD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iPresentAddressD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iPresentAddressD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPresentAddressDActionPerformed(evt);
            }
        });
        jPanel1.add(iPresentAddressD);
        iPresentAddressD.setBounds(1010, 490, 160, 30);

        jLabelACT20.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT20.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT20.setText("Parmanet  Address");
        jLabelACT20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT20);
        jLabelACT20.setBounds(280, 530, 200, 30);

        iParmanetAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iParmanetAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iParmanetAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iParmanetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iParmanetAddressActionPerformed(evt);
            }
        });
        jPanel1.add(iParmanetAddress);
        iParmanetAddress.setBounds(490, 530, 330, 30);

        jLabelACT21.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT21.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT21.setText("Post Office");
        jLabelACT21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT21);
        jLabelACT21.setBounds(830, 530, 170, 30);

        iParmanetAddressPO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iParmanetAddressPO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iParmanetAddressPO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iParmanetAddressPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iParmanetAddressPOActionPerformed(evt);
            }
        });
        jPanel1.add(iParmanetAddressPO);
        iParmanetAddressPO.setBounds(1010, 530, 160, 30);

        jLabelACT22.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT22.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT22.setText("Police Station");
        jLabelACT22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT22);
        jLabelACT22.setBounds(440, 570, 180, 30);

        iParmanetAddressPS.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iParmanetAddressPS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iParmanetAddressPS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iParmanetAddressPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iParmanetAddressPSActionPerformed(evt);
            }
        });
        jPanel1.add(iParmanetAddressPS);
        iParmanetAddressPS.setBounds(630, 570, 190, 30);

        jLabelACT23.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT23.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT23.setText("District");
        jLabelACT23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT23);
        jLabelACT23.setBounds(830, 570, 170, 30);

        iParmanetAddressD.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iParmanetAddressD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iParmanetAddressD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iParmanetAddressD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iParmanetAddressDActionPerformed(evt);
            }
        });
        jPanel1.add(iParmanetAddressD);
        iParmanetAddressD.setBounds(1010, 570, 160, 30);

        iAccountNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iAccountNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iAccountNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAccountNoActionPerformed(evt);
            }
        });
        jPanel1.add(iAccountNo);
        iAccountNo.setBounds(430, 210, 120, 30);

        jLabelACT25.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT25.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT25.setText("Account  No");
        jLabelACT25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT25);
        jLabelACT25.setBounds(280, 210, 140, 30);

        btnWF1.setBackground(new java.awt.Color(0, 102, 0));
        btnWF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnWF1.setForeground(new java.awt.Color(255, 255, 255));
        btnWF1.setText("Statement");
        btnWF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWF1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWF1);
        btnWF1.setBounds(20, 500, 230, 40);

        jProgressBar1.setBackground(new java.awt.Color(204, 255, 204));
        jProgressBar1.setForeground(new java.awt.Color(0, 153, 51));
        jProgressBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(500, 640, 200, 20);

        jProgressBar2.setBackground(new java.awt.Color(204, 255, 204));
        jProgressBar2.setForeground(new java.awt.Color(0, 153, 51));
        jProgressBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jProgressBar2);
        jProgressBar2.setBounds(280, 640, 190, 20);

        btnIcUpdate.setBackground(new java.awt.Color(0, 102, 0));
        btnIcUpdate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIcUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnIcUpdate.setText("Update");
        btnIcUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnIcUpdate);
        btnIcUpdate.setBounds(960, 630, 100, 30);

        btnSaveCA3.setBackground(new java.awt.Color(0, 102, 0));
        btnSaveCA3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSaveCA3.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCA3.setText("Upload From");
        btnSaveCA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCA3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveCA3);
        btnSaveCA3.setBounds(500, 600, 200, 30);

        btnSaveCA4.setBackground(new java.awt.Color(0, 102, 0));
        btnSaveCA4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSaveCA4.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCA4.setText("Share A/C");
        btnSaveCA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCA4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveCA4);
        btnSaveCA4.setBounds(830, 140, 140, 30);

        jLabelACT10.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT10.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT10.setText("Project Name");
        jLabelACT10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT10);
        jLabelACT10.setBounds(280, 250, 200, 30);

        jLabelACT27.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT27.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT27.setText("Owner  Name");
        jLabelACT27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT27);
        jLabelACT27.setBounds(280, 330, 200, 30);

        iName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNameActionPerformed(evt);
            }
        });
        jPanel1.add(iName);
        iName.setBounds(490, 330, 330, 30);

        jLabelACT26.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT26.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT26.setText("Project Duration");
        jLabelACT26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT26);
        jLabelACT26.setBounds(830, 330, 170, 30);

        iProjectDuration.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iProjectDuration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iProjectDuration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iProjectDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iProjectDurationActionPerformed(evt);
            }
        });
        jPanel1.add(iProjectDuration);
        iProjectDuration.setBounds(1010, 330, 160, 30);

        jLabelACT28.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT28.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT28.setText("Mother's Name");
        jLabelACT28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT28);
        jLabelACT28.setBounds(280, 410, 200, 30);

        iMotherName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iMotherName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iMotherName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iMotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMotherNameActionPerformed(evt);
            }
        });
        jPanel1.add(iMotherName);
        iMotherName.setBounds(490, 410, 330, 30);

        jLabelACT29.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT29.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT29.setText("Mobile No");
        jLabelACT29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT29);
        jLabelACT29.setBounds(830, 410, 170, 30);

        iMobilNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iMobilNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iMobilNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iMobilNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMobilNoActionPerformed(evt);
            }
        });
        jPanel1.add(iMobilNo);
        iMobilNo.setBounds(1010, 410, 160, 30);

        btnSaveCA5.setBackground(new java.awt.Color(0, 102, 0));
        btnSaveCA5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSaveCA5.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCA5.setText("Saving A/C");
        btnSaveCA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCA5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveCA5);
        btnSaveCA5.setBounds(670, 140, 140, 30);

        btnSaveCA6.setBackground(new java.awt.Color(0, 102, 0));
        btnSaveCA6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSaveCA6.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCA6.setText("Upload Picture");
        btnSaveCA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCA6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveCA6);
        btnSaveCA6.setBounds(280, 600, 190, 30);

        btnIcSave.setBackground(new java.awt.Color(0, 102, 0));
        btnIcSave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIcSave.setForeground(new java.awt.Color(255, 255, 255));
        btnIcSave.setText("Save");
        btnIcSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnIcSave);
        btnIcSave.setBounds(1070, 630, 100, 30);

        jLabel2.setBackground(new java.awt.Color(0, 102, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Create Investment A/C");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 164, 310, 30);

        btnIcExit.setBackground(new java.awt.Color(0, 102, 0));
        btnIcExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIcExit.setForeground(new java.awt.Color(255, 255, 255));
        btnIcExit.setText("Exit");
        btnIcExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnIcExit);
        btnIcExit.setBounds(720, 630, 100, 30);

        btnCiSave.setIcon(new javax.swing.ImageIcon("E:\\Git\\JavaSwing\\ssbbss\\src\\ssbbss\\Image\\background.png")); // NOI18N
        jPanel1.add(btnCiSave);
        btnCiSave.setBounds(0, 0, 1210, 670);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCAActionPerformed
        // TODO add your handling code here:

        System.out.println("Name: " + iProjectName.getText());
    }//GEN-LAST:event_btnSaveCAActionPerformed

    private void btnWFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWFActionPerformed
        new WelfareFundAcPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWFActionPerformed

    private void btnIcResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcResetActionPerformed
        JTextField temp = null;
        for (Component c : jPanel1.getComponents()) {
            if (c.getClass().toString().contains("JTextField")) {
                temp = (JTextField) c;
                temp.setText(null);
            }
        }
    }//GEN-LAST:event_btnIcResetActionPerformed

    private void btnIcSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcSearchActionPerformed
        CommonDAO obj = new CreateInvestmentCop();
        if (iAccountNo.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Enter an Account NO  ");
        } else {
            CreateInvestment ci = obj.getByAccountNo(Integer.parseInt(iAccountNo.getText()));
            
            //iAccountNo.setText(ci.getAccountNo());
            iFromNO.setText(ci.getFromNO());
            iCardNo.setText(ci.getCardNo());
            iProjectName.setText(ci.getProjectName());
            iProjectLocation.setText(ci.getProjectLocation());
            iInvestedAmount.setText(ci.getInvestedAmount());
            iStartDate.setText(ci.getStartDate());
            iProjectDuration.setText(ci.getProjectDuration());
            iName.setText(ci.getName());
            iMotherName.setText(ci.getMotherName());
            iFatherHusbendName.setText(ci.getFatherHusbendName());
            iPresentAddress.setText(ci.getPresentAddress());
            iParmanetAddress.setText(ci.getParmanetAddress());
            iNID.setText(ci.getNIDNo());
            iMobilNo.setText(ci.getMobileNo());
        }
    }//GEN-LAST:event_btnIcSearchActionPerformed

    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCAActionPerformed

    private void btnSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAActionPerformed
        new SavingAcPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSAActionPerformed

    private void btnSHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSHAActionPerformed
        new ShareAcPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSHAActionPerformed

    private void btnIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIAActionPerformed
        new InvestmentAcPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIAActionPerformed

    private void iStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iStartDateActionPerformed

    private void iProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iProjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iProjectNameActionPerformed

    private void iFatherHusbendNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iFatherHusbendNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iFatherHusbendNameActionPerformed

    private void iProjectLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iProjectLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iProjectLocationActionPerformed

    private void iNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNIDActionPerformed

    private void iPresentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPresentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iPresentAddressActionPerformed

    private void iCardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCardNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCardNoActionPerformed

    private void iInvestedAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iInvestedAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iInvestedAmountActionPerformed

    private void iFromNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iFromNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iFromNOActionPerformed

    private void iPresentAddressPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPresentAddressPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iPresentAddressPOActionPerformed

    private void iPresentAddressPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPresentAddressPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iPresentAddressPSActionPerformed

    private void iPresentAddressDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPresentAddressDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iPresentAddressDActionPerformed

    private void iParmanetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iParmanetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iParmanetAddressActionPerformed

    private void iParmanetAddressPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iParmanetAddressPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iParmanetAddressPOActionPerformed

    private void iParmanetAddressPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iParmanetAddressPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iParmanetAddressPSActionPerformed

    private void iParmanetAddressDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iParmanetAddressDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iParmanetAddressDActionPerformed

    private void iAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAccountNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iAccountNoActionPerformed

    private void btnWF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWF1ActionPerformed
        new StatementPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWF1ActionPerformed

    private void btnCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCAMouseClicked


    }//GEN-LAST:event_btnCAMouseClicked

    private void btnIcUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcUpdateActionPerformed
        int AccountNo = Integer.parseInt(iAccountNo.getText());
        String FromNO = iFromNO.getText();
        String CardNo = iCardNo.getText();
        String ProjectName = iProjectName.getText();
        String ProjectLocation = iProjectLocation.getText();
        String Name = iName.getText();
        String MotherName = iMotherName.getText();
        String FatherHusbendName = iFatherHusbendName.getText();
        String PresentAddress = iPresentAddress.getText() + " " + iPresentAddressPO.getText() + " " + iPresentAddressPS.getText() + " " + iPresentAddressD.getText();
        String ParmanetAddress = iParmanetAddress.getText() + " " + iParmanetAddressPO.getText() + " " + iParmanetAddressPS.getText() + " " + iParmanetAddressD.getText();
        String StartDate = iStartDate.getText();
        String InvestedAmount = iInvestedAmount.getText();
        String ProjectDuration = iProjectDuration.getText();
        String NIDNo = iNID.getText();
        String MobileNo = iMobilNo.getText();

        CreateInvestment ci = new CreateInvestment(AccountNo, FromNO, CardNo, ProjectName, ProjectLocation, Name, MotherName, FatherHusbendName, PresentAddress, ParmanetAddress, StartDate, InvestedAmount, ProjectDuration, NIDNo, MobileNo);
        CreateInvestmentCop co = new CreateInvestmentCop();
        co.update(ci);
        

    }//GEN-LAST:event_btnIcUpdateActionPerformed

    private void btnSaveCA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveCA3ActionPerformed

    private void btnSaveCA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCA4ActionPerformed
        new CreateShareAccountPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSaveCA4ActionPerformed

    private void iNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNameActionPerformed

    private void iProjectDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iProjectDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iProjectDurationActionPerformed

    private void iMotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMotherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iMotherNameActionPerformed

    private void iMobilNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMobilNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iMobilNoActionPerformed

    private void btnSaveCA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCA5ActionPerformed
        new CreateSavingAccountPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSaveCA5ActionPerformed

    private void btnSaveCA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCA6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveCA6ActionPerformed

    private void btnIcExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIcExitActionPerformed

    private void btnIcSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcSaveActionPerformed
       int AccountNo = Integer.parseInt(iAccountNo.getText());
        String FromNO = iFromNO.getText();
        String CardNo = iCardNo.getText();
        String ProjectName = iProjectName.getText();
        String ProjectLocation = iProjectLocation.getText();
        String Name = iName.getText();
        String MotherName = iMotherName.getText();
        String FatherHusbendName = iFatherHusbendName.getText();
        String PresentAddress = iPresentAddress.getText() + " " + iPresentAddressPO.getText() + " " + iPresentAddressPS.getText() + " " + iPresentAddressD.getText();
        String ParmanetAddress = iParmanetAddress.getText() + " " + iParmanetAddressPO.getText() + " " + iParmanetAddressPS.getText() + " " + iParmanetAddressD.getText();
        String StartDate = iStartDate .getText();
        String InvestedAmount = iInvestedAmount.getText();
        String ProjectDuration = iProjectDuration.getText();
        String NIDNo = iNID.getText();
        String MobileNo = iMobilNo.getText();

        
        Connection con = null;
        PreparedStatement pst = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbssbbss", "root", "1234");
            pst = con.prepareStatement("insert into investmentinfo values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setInt(1, AccountNo);
            pst.setString(2, FromNO);
            pst.setString(3, CardNo);
            pst.setString(4, ProjectName);
            pst.setString(5, ProjectLocation);
            pst.setString(6, InvestedAmount);
            pst.setString(7, StartDate);
            pst.setString(8, ProjectDuration);
            pst.setString(9, Name);
            pst.setString(10, MotherName);
            pst.setString(11, FatherHusbendName);
            pst.setString(12, PresentAddress);
            pst.setString(13, ParmanetAddress);
            pst.setString(14, NIDNo);
            pst.setString(15, MobileNo);
           
            int i = pst.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Data is Saved");
            } else {
                JOptionPane.showMessageDialog(null, "Data is Not Saved");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnIcSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateInvestmentAccountPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateInvestmentAccountPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateInvestmentAccountPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateInvestmentAccountPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateInvestmentAccountPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountType2;
    private javax.swing.JButton btnCA;
    private javax.swing.JLabel btnCiSave;
    private javax.swing.JButton btnIA;
    private javax.swing.JButton btnIcExit;
    private javax.swing.JButton btnIcReset;
    private javax.swing.JButton btnIcSave;
    private javax.swing.JButton btnIcSearch;
    private javax.swing.JButton btnIcUpdate;
    private javax.swing.JButton btnSA;
    private javax.swing.JButton btnSHA;
    private javax.swing.JButton btnSaveCA;
    private javax.swing.JButton btnSaveCA3;
    private javax.swing.JButton btnSaveCA4;
    private javax.swing.JButton btnSaveCA5;
    private javax.swing.JButton btnSaveCA6;
    private javax.swing.JButton btnWF;
    private javax.swing.JButton btnWF1;
    private javax.swing.JTextField iAccountNo;
    private javax.swing.JTextField iCardNo;
    private javax.swing.JTextField iFatherHusbendName;
    private javax.swing.JTextField iFromNO;
    private javax.swing.JTextField iInvestedAmount;
    private javax.swing.JTextField iMobilNo;
    private javax.swing.JTextField iMotherName;
    private javax.swing.JTextField iNID;
    private javax.swing.JTextField iName;
    private javax.swing.JTextField iParmanetAddress;
    private javax.swing.JTextField iParmanetAddressD;
    private javax.swing.JTextField iParmanetAddressPO;
    private javax.swing.JTextField iParmanetAddressPS;
    private javax.swing.JTextField iPresentAddress;
    private javax.swing.JTextField iPresentAddressD;
    private javax.swing.JTextField iPresentAddressPO;
    private javax.swing.JTextField iPresentAddressPS;
    private javax.swing.JTextField iProjectDuration;
    private javax.swing.JTextField iProjectLocation;
    private javax.swing.JTextField iProjectName;
    private javax.swing.JTextField iStartDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelACT;
    private javax.swing.JLabel jLabelACT10;
    private javax.swing.JLabel jLabelACT13;
    private javax.swing.JLabel jLabelACT14;
    private javax.swing.JLabel jLabelACT15;
    private javax.swing.JLabel jLabelACT17;
    private javax.swing.JLabel jLabelACT18;
    private javax.swing.JLabel jLabelACT19;
    private javax.swing.JLabel jLabelACT20;
    private javax.swing.JLabel jLabelACT21;
    private javax.swing.JLabel jLabelACT22;
    private javax.swing.JLabel jLabelACT23;
    private javax.swing.JLabel jLabelACT25;
    private javax.swing.JLabel jLabelACT26;
    private javax.swing.JLabel jLabelACT27;
    private javax.swing.JLabel jLabelACT28;
    private javax.swing.JLabel jLabelACT29;
    private javax.swing.JLabel jLabelACT5;
    private javax.swing.JLabel jLabelACT6;
    private javax.swing.JLabel jLabelACT7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
