/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sadria.view;

import com.sadria.Dao.InvestmentDao;
import com.sadria.Dao.PersonDao;
import com.sadria.Dao.SummaryDao;
import com.sadria.DaoImp.InvestmentDaoImp;
import com.sadria.DaoImp.PersonDaoImp;
import com.sadria.DaoImp.SummaryDaoImp;
import com.sadria.pojo.Investment;
import com.sadria.pojo.Person;
import com.sadria.pojo.Summary;
import java.awt.Component;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Blob;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class investmentView extends javax.swing.JFrame {

    /**
     * Creates new form PersonInfoview
     */
    public investmentView() {
        initComponents();
        setLocationRelativeTo(null);
    }
    String fileName = null;
    byte[] person_img = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCreateAccount = new javax.swing.JLabel();
        lblCreateAccount1 = new javax.swing.JLabel();
        lblCreateAccount2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        btnUplodeImg = new javax.swing.JButton();
        jLabelACT25 = new javax.swing.JLabel();
        txtAccountNo = new javax.swing.JTextField();
        jLabelACT10 = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        jLabelACT5 = new javax.swing.JLabel();
        txtProjectLocation = new javax.swing.JTextField();
        txtTotalInvestment = new javax.swing.JTextField();
        jLabelACT = new javax.swing.JLabel();
        txtDateofBirth = new javax.swing.JTextField();
        jLabelACT6 = new javax.swing.JLabel();
        txtNid = new javax.swing.JTextField();
        jLabelACT7 = new javax.swing.JLabel();
        comGender = new javax.swing.JComboBox<>();
        jLabelACT1 = new javax.swing.JLabel();
        txtReligion = new javax.swing.JTextField();
        jLabelACT8 = new javax.swing.JLabel();
        txtPresentAddress = new javax.swing.JTextField();
        jLabelACT20 = new javax.swing.JLabel();
        txtParmanetAddress = new javax.swing.JTextField();
        jLabelACT4 = new javax.swing.JLabel();
        txtMobilNo = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabelACT14 = new javax.swing.JLabel();
        jLabelACT17 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabelACT18 = new javax.swing.JLabel();
        txtProjectDuration = new javax.swing.JTextField();
        jLabelACT19 = new javax.swing.JLabel();
        txtDirectorName = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabelACT26 = new javax.swing.JLabel();
        sAccountNo1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvestmentA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\IDB\\Git\\JavaSwing\\SadriaSocity\\src\\com\\sadria\\img\\hedline2.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        lblCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateAccount.setText("Statement");

        lblCreateAccount1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateAccount1.setText("Create Account");
        lblCreateAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccount1MouseClicked(evt);
            }
        });

        lblCreateAccount2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateAccount2.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateAccount2.setText("Transtion");
        lblCreateAccount2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccount2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateAccount2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblCreateAccount1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblCreateAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(lblCreateAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblImg.setBorder(new javax.swing.border.MatteBorder(null));

        btnUplodeImg.setBackground(new java.awt.Color(0, 102, 51));
        btnUplodeImg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUplodeImg.setForeground(new java.awt.Color(255, 255, 255));
        btnUplodeImg.setText("Upload Image");
        btnUplodeImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUplodeImgActionPerformed(evt);
            }
        });

        jLabelACT25.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT25.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT25.setText("Account  No");
        jLabelACT25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtAccountNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtAccountNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccountNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNoActionPerformed(evt);
            }
        });

        jLabelACT10.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT10.setText("Project Name");
        jLabelACT10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtProjectName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtProjectName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProjectName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectNameActionPerformed(evt);
            }
        });

        jLabelACT5.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT5.setText("Project Location");
        jLabelACT5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtProjectLocation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtProjectLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProjectLocation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtProjectLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectLocationActionPerformed(evt);
            }
        });

        txtTotalInvestment.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtTotalInvestment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalInvestment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotalInvestment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalInvestmentActionPerformed(evt);
            }
        });

        jLabelACT.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT.setText("Religion");
        jLabelACT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtDateofBirth.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtDateofBirth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDateofBirth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDateofBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateofBirthActionPerformed(evt);
            }
        });

        jLabelACT6.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT6.setText("NID No");
        jLabelACT6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNid.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtNid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNidActionPerformed(evt);
            }
        });

        jLabelACT7.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT7.setText("Gender");
        jLabelACT7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        comGender.setBackground(new java.awt.Color(0, 102, 51));
        comGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comGender.setForeground(new java.awt.Color(255, 255, 255));
        comGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "FeMale" }));

        jLabelACT1.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT1.setText("Date of Birth");
        jLabelACT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtReligion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtReligion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReligion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReligionActionPerformed(evt);
            }
        });

        jLabelACT8.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT8.setText("Present Address");
        jLabelACT8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtPresentAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPresentAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPresentAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPresentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentAddressActionPerformed(evt);
            }
        });

        jLabelACT20.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT20.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT20.setText("Parmanet  Address");
        jLabelACT20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtParmanetAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtParmanetAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtParmanetAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtParmanetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParmanetAddressActionPerformed(evt);
            }
        });

        jLabelACT4.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT4.setText("Mobile No");
        jLabelACT4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtMobilNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtMobilNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMobilNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtMobilNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobilNoActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 102, 51));
        btnExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 102, 51));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 102, 51));
        btnSave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabelACT14.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT14.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT14.setText("Invested Amount");
        jLabelACT14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelACT17.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT17.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT17.setText("Start Date ");
        jLabelACT17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtStartDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtStartDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStartDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        jLabelACT18.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT18.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT18.setText("Project Duration");
        jLabelACT18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtProjectDuration.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtProjectDuration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProjectDuration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtProjectDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectDurationActionPerformed(evt);
            }
        });

        jLabelACT19.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT19.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT19.setText("Director Name");
        jLabelACT19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtDirectorName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtDirectorName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDirectorName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDirectorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorNameActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 102, 51));
        btnReset.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 102, 51));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabelACT26.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT26.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT26.setText("Amount");
        jLabelACT26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sAccountNo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sAccountNo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sAccountNo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sAccountNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAccountNo1ActionPerformed(evt);
            }
        });

        tblInvestmentA.setBackground(new java.awt.Color(204, 255, 204));
        tblInvestmentA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblInvestmentA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblInvestmentA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Account No", "Project Name", "Project Location", "Start Date", "Director Name", "Total Investment", "Return", "Balance", "Project Duration"
            }
        ));
        jScrollPane1.setViewportView(tblInvestmentA);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sAccountNo1)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUplodeImg, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addComponent(jLabelACT25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelACT26, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelACT10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtProjectName))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelACT5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtProjectLocation))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelACT8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtPresentAddress))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelACT20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtParmanetAddress))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelACT14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelACT17, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelACT18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtProjectDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelACT19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtDirectorName))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelACT7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comGender, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelACT1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelACT4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMobilNo))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelACT, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelACT6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNid))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelACT10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelACT5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProjectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelACT14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelACT17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelACT18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProjectDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelACT19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirectorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelACT7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelACT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelACT4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMobilNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelACT6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelACT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelACT8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelACT25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPresentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUplodeImg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelACT20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtParmanetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelACT26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sAccountNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNoActionPerformed

    private void txtProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectNameActionPerformed

    private void txtProjectLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectLocationActionPerformed

    private void txtTotalInvestmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalInvestmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalInvestmentActionPerformed

    private void txtDateofBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateofBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateofBirthActionPerformed

    private void txtNidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNidActionPerformed

    private void txtReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReligionActionPerformed

    private void txtPresentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentAddressActionPerformed

    private void txtParmanetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParmanetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParmanetAddressActionPerformed

    private void txtMobilNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobilNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobilNoActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "SSBBSS System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        JTextField temp = null;
        for (Component c : jPanel1.getComponents()) {
            if (c.getClass().toString().contains("JTextField")) {
                temp = (JTextField) c;
                temp.setText(null);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        InvestmentDao iDao = new InvestmentDaoImp();
        String accountNo = txtAccountNo.getText();
        String projectName = txtProjectName.getText();
        String projectLocation = txtProjectLocation.getText();
        Double totalInvestment = Double.parseDouble(txtTotalInvestment.getText());
        Date txtStartDate = new java.sql.Date(System.currentTimeMillis());
        int projectDuration = Integer.parseInt(txtProjectDuration.getText());
        String directorName = txtDirectorName.getText();
        String gender = comGender.getItemAt(comGender.getSelectedIndex());
        String religion = txtReligion.getText();
        String dateofBirth = txtDateofBirth.getText();
        String nIDNo = txtNid.getText();
        String mobileNo = txtMobilNo.getText();
        String presentAddress = txtPresentAddress.getText();
        String parmanetAddress = txtParmanetAddress.getText();
        Blob picture = null;

        try {
            Investment i = new Investment(accountNo, projectName, projectLocation, totalInvestment, txtStartDate, projectDuration, directorName, gender, religion, dateofBirth, nIDNo, mobileNo, presentAddress, parmanetAddress, picture);
            iDao.save(i);

//            SummaryDao summaryDao=new SummaryDaoImp();
//            Summary summary=new Summary(accountNo, name, savingType, Integer.parseInt(sAnnunity.getText().trim()), new Date(),Integer.parseInt(sAnnunity.getText().trim()), 0, Integer.parseInt(sAnnunity.getText().trim()),1,new Date(), 0);
//            summaryDao.save(summary);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void lblCreateAccount2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccount2MouseClicked
        this.setVisible(false);
        new Transtionview().setVisible(true);
    }//GEN-LAST:event_lblCreateAccount2MouseClicked

    private void lblCreateAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccount1MouseClicked

        this.setVisible(true);
        new Transtionview().setVisible(false);
    }//GEN-LAST:event_lblCreateAccount1MouseClicked

    private void btnUplodeImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUplodeImgActionPerformed
        // TODO add your handling code here:
        JFileChooser chosser = new JFileChooser();
        chosser.showOpenDialog(null);
        File file = chosser.getSelectedFile();
        fileName = file.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH));
        lblImg.setIcon(imageIcon);
        try {
            File image = new File(fileName);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != 1;) {
                bos.write(buf, 0, readNum);
            }
            person_img = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnUplodeImgActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtProjectDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectDurationActionPerformed

    private void txtDirectorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorNameActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        InvestmentDao iDao = new InvestmentDaoImp();
        Investment investment = iDao.getInvestmentinfoByAccontNo(txtAccountNo.getText().trim());
       
        txtProjectName.setText(investment.getProjectName());
        txtProjectLocation.setText(investment.getProjectLocation());
        txtTotalInvestment.setText(investment.getTotalInvestment()+"");
        txtStartDate.setText(investment.getStartDate()+"");
        txtProjectDuration.setText(investment.getProjectDuration()+"");
        txtDirectorName.setText(investment.getDirectortName());
        comGender.getItemAt(comGender.getSelectedIndex());
        txtReligion.setText(investment.getReligion());;
        txtDateofBirth.setText(investment.getDateofBirth());
        txtNid.setText(investment.getnIDNo());
        txtMobilNo.setText(investment.getMobileNo());
        txtPresentAddress.setText(investment.getPresentAddress());
        txtParmanetAddress.setText(investment.getParmanetAddress());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void sAccountNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAccountNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sAccountNo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(investmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(investmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(investmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(investmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new investmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUplodeImg;
    private javax.swing.JComboBox<String> comGender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelACT;
    private javax.swing.JLabel jLabelACT1;
    private javax.swing.JLabel jLabelACT10;
    private javax.swing.JLabel jLabelACT14;
    private javax.swing.JLabel jLabelACT17;
    private javax.swing.JLabel jLabelACT18;
    private javax.swing.JLabel jLabelACT19;
    private javax.swing.JLabel jLabelACT20;
    private javax.swing.JLabel jLabelACT25;
    private javax.swing.JLabel jLabelACT26;
    private javax.swing.JLabel jLabelACT4;
    private javax.swing.JLabel jLabelACT5;
    private javax.swing.JLabel jLabelACT6;
    private javax.swing.JLabel jLabelACT7;
    private javax.swing.JLabel jLabelACT8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JLabel lblCreateAccount1;
    private javax.swing.JLabel lblCreateAccount2;
    private javax.swing.JLabel lblImg;
    private javax.swing.JTextField sAccountNo1;
    private javax.swing.JTable tblInvestmentA;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDirectorName;
    private javax.swing.JTextField txtMobilNo;
    private javax.swing.JTextField txtNid;
    private javax.swing.JTextField txtParmanetAddress;
    private javax.swing.JTextField txtPresentAddress;
    private javax.swing.JTextField txtProjectDuration;
    private javax.swing.JTextField txtProjectLocation;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextField txtReligion;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTotalInvestment;
    // End of variables declaration//GEN-END:variables
}
