/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ssbbss;

/**
 *
 * @author Md Yasin Arif
 */
public class CreateAccountPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public CreateAccountPage() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSaveCA = new javax.swing.JButton();
        btnWF = new javax.swing.JButton();
        btnResetCA = new javax.swing.JButton();
        btnExitCA1 = new javax.swing.JButton();
        btnCA = new javax.swing.JButton();
        btnSA = new javax.swing.JButton();
        btnSHA = new javax.swing.JButton();
        btnIA = new javax.swing.JButton();
        jLabelACT = new javax.swing.JLabel();
        AccountType = new javax.swing.JComboBox<>();
        jLabelACT1 = new javax.swing.JLabel();
        jTextFielduserName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabelACT2 = new javax.swing.JLabel();
        jTextFielduserName2 = new javax.swing.JTextField();
        jLabelACT4 = new javax.swing.JLabel();
        jTextFielduserName3 = new javax.swing.JTextField();
        jLabelACT5 = new javax.swing.JLabel();
        jTextFielduserName4 = new javax.swing.JTextField();
        jLabelACT6 = new javax.swing.JLabel();
        jTextFielduserName5 = new javax.swing.JTextField();
        jLabelACT7 = new javax.swing.JLabel();
        jTextFielduserName6 = new javax.swing.JTextField();
        AccountType1 = new javax.swing.JComboBox<>();
        jLabelACT9 = new javax.swing.JLabel();
        jTextFielduserName8 = new javax.swing.JTextField();
        jLabelACT11 = new javax.swing.JLabel();
        jTextFielduserName10 = new javax.swing.JTextField();
        jLabelACT12 = new javax.swing.JLabel();
        jTextFielduserName11 = new javax.swing.JTextField();
        jLabelACT13 = new javax.swing.JLabel();
        jTextFielduserName12 = new javax.swing.JTextField();
        jLabelACT14 = new javax.swing.JLabel();
        jTextFielduserName13 = new javax.swing.JTextField();
        jLabelACT15 = new javax.swing.JLabel();
        jTextFielduserName14 = new javax.swing.JTextField();
        jLabelACT16 = new javax.swing.JLabel();
        AccountType2 = new javax.swing.JComboBox<>();
        jLabelACT17 = new javax.swing.JLabel();
        jLabelACT18 = new javax.swing.JLabel();
        jTextFielduserName16 = new javax.swing.JTextField();
        jTextFielduserName15 = new javax.swing.JTextField();
        jLabelACT19 = new javax.swing.JLabel();
        jTextFielduserName17 = new javax.swing.JTextField();
        jLabelACT20 = new javax.swing.JLabel();
        jTextFielduserName18 = new javax.swing.JTextField();
        jLabelACT21 = new javax.swing.JLabel();
        jTextFielduserName19 = new javax.swing.JTextField();
        jLabelACT22 = new javax.swing.JLabel();
        jTextFielduserName20 = new javax.swing.JTextField();
        jLabelACT23 = new javax.swing.JLabel();
        jTextFielduserName21 = new javax.swing.JTextField();
        jLabelACT24 = new javax.swing.JLabel();
        jTextFielduserName22 = new javax.swing.JTextField();
        jTextFielduserName23 = new javax.swing.JTextField();
        jLabelACT25 = new javax.swing.JLabel();
        btnWF1 = new javax.swing.JButton();
        jLabelACT3 = new javax.swing.JLabel();
        jLabelACT8 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnSaveCA.setBackground(new java.awt.Color(0, 102, 0));
        btnSaveCA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSaveCA.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCA.setText("Save");
        btnSaveCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCAActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveCA);
        btnSaveCA.setBounds(1070, 630, 100, 30);

        btnWF.setBackground(new java.awt.Color(0, 102, 0));
        btnWF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnWF.setForeground(new java.awt.Color(255, 255, 255));
        btnWF.setText("Welfare Fund");
        btnWF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWFActionPerformed(evt);
            }
        });
        jPanel1.add(btnWF);
        btnWF.setBounds(20, 440, 230, 40);

        btnResetCA.setBackground(new java.awt.Color(0, 102, 0));
        btnResetCA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnResetCA.setForeground(new java.awt.Color(255, 255, 255));
        btnResetCA.setText("Reset");
        btnResetCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCAActionPerformed(evt);
            }
        });
        jPanel1.add(btnResetCA);
        btnResetCA.setBounds(950, 630, 100, 30);

        btnExitCA1.setBackground(new java.awt.Color(0, 102, 0));
        btnExitCA1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExitCA1.setForeground(new java.awt.Color(255, 255, 255));
        btnExitCA1.setText("Exit");
        btnExitCA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitCA1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExitCA1);
        btnExitCA1.setBounds(830, 630, 100, 30);

        btnCA.setBackground(new java.awt.Color(0, 102, 0));
        btnCA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCA.setForeground(new java.awt.Color(255, 255, 255));
        btnCA.setText("Create Account");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });
        jPanel1.add(btnCA);
        btnCA.setBounds(20, 200, 230, 40);

        btnSA.setBackground(new java.awt.Color(0, 102, 0));
        btnSA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSA.setForeground(new java.awt.Color(255, 255, 255));
        btnSA.setText("Saving Account");
        btnSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAActionPerformed(evt);
            }
        });
        jPanel1.add(btnSA);
        btnSA.setBounds(20, 260, 230, 40);

        btnSHA.setBackground(new java.awt.Color(0, 102, 0));
        btnSHA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSHA.setForeground(new java.awt.Color(255, 255, 255));
        btnSHA.setText("Share Account");
        btnSHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSHAActionPerformed(evt);
            }
        });
        jPanel1.add(btnSHA);
        btnSHA.setBounds(20, 320, 230, 40);

        btnIA.setBackground(new java.awt.Color(0, 102, 0));
        btnIA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIA.setForeground(new java.awt.Color(255, 255, 255));
        btnIA.setText("Investment Account");
        btnIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIAActionPerformed(evt);
            }
        });
        jPanel1.add(btnIA);
        btnIA.setBounds(20, 380, 230, 40);

        jLabelACT.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT.setText("Date of Dirth");
        jLabelACT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT);
        jLabelACT.setBounds(830, 200, 170, 30);

        AccountType.setBackground(new java.awt.Color(53, 255, 0));
        AccountType.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AccountType.setForeground(new java.awt.Color(0, 153, 0));
        AccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Monthly", "Fixed" }));
        AccountType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(AccountType);
        AccountType.setBounds(490, 480, 110, 30);

        jLabelACT1.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelACT1.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT1.setText("Account Type");
        jLabelACT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT1);
        jLabelACT1.setBounds(670, 130, 240, 50);

        jTextFielduserName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName);
        jTextFielduserName.setBounds(1010, 200, 160, 30);

        txtName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName);
        txtName.setBounds(490, 200, 330, 30);

        jLabelACT2.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT2.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT2.setText("Upload From");
        jLabelACT2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT2);
        jLabelACT2.setBounds(500, 600, 200, 30);

        jTextFielduserName2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName2);
        jTextFielduserName2.setBounds(490, 280, 330, 30);

        jLabelACT4.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT4.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT4.setText("Mobile No");
        jLabelACT4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT4);
        jLabelACT4.setBounds(870, 480, 130, 30);

        jTextFielduserName3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName3);
        jTextFielduserName3.setBounds(1010, 480, 160, 30);

        jLabelACT5.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT5.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT5.setText("Mother's Name");
        jLabelACT5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT5);
        jLabelACT5.setBounds(280, 240, 200, 30);

        jTextFielduserName4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName4);
        jTextFielduserName4.setBounds(490, 240, 330, 30);

        jLabelACT6.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT6.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT6.setText("NID No");
        jLabelACT6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT6);
        jLabelACT6.setBounds(830, 280, 170, 30);

        jTextFielduserName5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName5);
        jTextFielduserName5.setBounds(1010, 280, 160, 30);

        jLabelACT7.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT7.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT7.setText("Present Address");
        jLabelACT7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT7);
        jLabelACT7.setBounds(280, 320, 200, 30);

        jTextFielduserName6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName6);
        jTextFielduserName6.setBounds(490, 320, 360, 30);

        AccountType1.setBackground(new java.awt.Color(0, 102, 0));
        AccountType1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AccountType1.setForeground(new java.awt.Color(255, 255, 255));
        AccountType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving Account", "Share Account", "Investment Account" }));
        AccountType1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(AccountType1);
        AccountType1.setBounds(930, 130, 230, 50);

        jLabelACT9.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT9.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT9.setText("Nomine's Name");
        jLabelACT9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT9);
        jLabelACT9.setBounds(280, 560, 200, 30);

        jTextFielduserName8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName8);
        jTextFielduserName8.setBounds(490, 560, 230, 30);

        jLabelACT11.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT11.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT11.setText("Relations");
        jLabelACT11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT11);
        jLabelACT11.setBounds(730, 560, 120, 30);

        jTextFielduserName10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName10);
        jTextFielduserName10.setBounds(860, 560, 100, 30);

        jLabelACT12.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT12.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT12.setText("Savings Type");
        jLabelACT12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT12);
        jLabelACT12.setBounds(280, 480, 200, 30);

        jTextFielduserName11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName11);
        jTextFielduserName11.setBounds(780, 480, 80, 30);

        jLabelACT13.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT13.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT13.setText("Card No");
        jLabelACT13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT13);
        jLabelACT13.setBounds(910, 520, 100, 30);

        jTextFielduserName12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName12ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName12);
        jTextFielduserName12.setBounds(1020, 520, 150, 30);

        jLabelACT14.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT14.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT14.setText("Admission Date");
        jLabelACT14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT14);
        jLabelACT14.setBounds(830, 240, 170, 30);

        jTextFielduserName13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName13);
        jTextFielduserName13.setBounds(1010, 240, 160, 30);

        jLabelACT15.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT15.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT15.setText("From NO");
        jLabelACT15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT15);
        jLabelACT15.setBounds(610, 520, 100, 30);

        jTextFielduserName14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName14);
        jTextFielduserName14.setBounds(720, 520, 170, 30);

        jLabelACT16.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT16.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT16.setText("Savings Amount");
        jLabelACT16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT16);
        jLabelACT16.setBounds(610, 480, 160, 30);

        AccountType2.setBackground(new java.awt.Color(53, 255, 0));
        AccountType2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AccountType2.setForeground(new java.awt.Color(0, 153, 0));
        AccountType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Father's Name", "Husbend's Name" }));
        AccountType2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(AccountType2);
        AccountType2.setBounds(280, 280, 200, 30);

        jLabelACT17.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT17.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT17.setText("Post Office");
        jLabelACT17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT17);
        jLabelACT17.setBounds(860, 320, 130, 30);

        jLabelACT18.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT18.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT18.setText("Police Station");
        jLabelACT18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT18);
        jLabelACT18.setBounds(440, 360, 180, 30);

        jTextFielduserName16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName16ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName16);
        jTextFielduserName16.setBounds(630, 360, 170, 30);

        jTextFielduserName15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName15);
        jTextFielduserName15.setBounds(1000, 320, 170, 30);

        jLabelACT19.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT19.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT19.setText("District");
        jLabelACT19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT19);
        jLabelACT19.setBounds(810, 360, 180, 30);

        jTextFielduserName17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName17ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName17);
        jTextFielduserName17.setBounds(1000, 360, 170, 30);

        jLabelACT20.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT20.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT20.setText("Parmanet  Address");
        jLabelACT20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT20);
        jLabelACT20.setBounds(280, 400, 200, 30);

        jTextFielduserName18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName18ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName18);
        jTextFielduserName18.setBounds(490, 400, 360, 30);

        jLabelACT21.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT21.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT21.setText("Post Office");
        jLabelACT21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT21);
        jLabelACT21.setBounds(860, 400, 130, 30);

        jTextFielduserName19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName19ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName19);
        jTextFielduserName19.setBounds(1000, 400, 170, 30);

        jLabelACT22.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT22.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT22.setText("Police Station");
        jLabelACT22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT22);
        jLabelACT22.setBounds(440, 440, 180, 30);

        jTextFielduserName20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName20ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName20);
        jTextFielduserName20.setBounds(630, 440, 170, 30);

        jLabelACT23.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT23.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT23.setText("District");
        jLabelACT23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT23);
        jLabelACT23.setBounds(810, 440, 180, 30);

        jTextFielduserName21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName21ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName21);
        jTextFielduserName21.setBounds(1000, 440, 170, 30);

        jLabelACT24.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT24.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT24.setText("Share %");
        jLabelACT24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT24);
        jLabelACT24.setBounds(970, 560, 120, 30);

        jTextFielduserName22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName22ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName22);
        jTextFielduserName22.setBounds(1100, 560, 70, 30);

        jTextFielduserName23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFielduserName23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextFielduserName23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserName23ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielduserName23);
        jTextFielduserName23.setBounds(430, 520, 170, 30);

        jLabelACT25.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT25.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT25.setText("Account  No");
        jLabelACT25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT25);
        jLabelACT25.setBounds(280, 520, 140, 30);

        btnWF1.setBackground(new java.awt.Color(0, 102, 0));
        btnWF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnWF1.setForeground(new java.awt.Color(255, 255, 255));
        btnWF1.setText("Statement");
        btnWF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWF1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWF1);
        btnWF1.setBounds(20, 490, 230, 40);

        jLabelACT3.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT3.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT3.setText("Name");
        jLabelACT3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT3);
        jLabelACT3.setBounds(280, 200, 200, 30);

        jLabelACT8.setBackground(new java.awt.Color(153, 255, 0));
        jLabelACT8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT8.setForeground(new java.awt.Color(0, 153, 0));
        jLabelACT8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT8.setText("Upload Picture");
        jLabelACT8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelACT8);
        jLabelACT8.setBounds(280, 600, 200, 30);

        jProgressBar1.setBackground(new java.awt.Color(204, 255, 204));
        jProgressBar1.setForeground(new java.awt.Color(0, 153, 51));
        jProgressBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(500, 640, 200, 20);

        jProgressBar2.setBackground(new java.awt.Color(204, 255, 204));
        jProgressBar2.setForeground(new java.awt.Color(0, 153, 51));
        jProgressBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jProgressBar2);
        jProgressBar2.setBounds(280, 640, 190, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssbbss/Image/background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCAActionPerformed
        // TODO add your handling code here:
      
        System.out.println("Name: "+txtName.getText());
    }//GEN-LAST:event_btnSaveCAActionPerformed

    private void btnWFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWFActionPerformed

    private void btnResetCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetCAActionPerformed

    private void btnExitCA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitCA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitCA1ActionPerformed

    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCAActionPerformed

    private void btnSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSAActionPerformed

    private void btnSHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSHAActionPerformed

    private void btnIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIAActionPerformed

    private void jTextFielduserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserNameActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jTextFielduserName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName2ActionPerformed

    private void jTextFielduserName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName3ActionPerformed

    private void jTextFielduserName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName4ActionPerformed

    private void jTextFielduserName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName5ActionPerformed

    private void jTextFielduserName6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName6ActionPerformed

    private void jTextFielduserName8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName8ActionPerformed

    private void jTextFielduserName10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName10ActionPerformed

    private void jTextFielduserName11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName11ActionPerformed

    private void jTextFielduserName12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName12ActionPerformed

    private void jTextFielduserName13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName13ActionPerformed

    private void jTextFielduserName14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName14ActionPerformed

    private void jTextFielduserName15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName15ActionPerformed

    private void jTextFielduserName16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName16ActionPerformed

    private void jTextFielduserName17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName17ActionPerformed

    private void jTextFielduserName18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName18ActionPerformed

    private void jTextFielduserName19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName19ActionPerformed

    private void jTextFielduserName20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName20ActionPerformed

    private void jTextFielduserName21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName21ActionPerformed

    private void jTextFielduserName22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName22ActionPerformed

    private void jTextFielduserName23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserName23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserName23ActionPerformed

    private void btnWF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWF1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountType;
    private javax.swing.JComboBox<String> AccountType1;
    private javax.swing.JComboBox<String> AccountType2;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnExitCA1;
    private javax.swing.JButton btnIA;
    private javax.swing.JButton btnResetCA;
    private javax.swing.JButton btnSA;
    private javax.swing.JButton btnSHA;
    private javax.swing.JButton btnSaveCA;
    private javax.swing.JButton btnWF;
    private javax.swing.JButton btnWF1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelACT;
    private javax.swing.JLabel jLabelACT1;
    private javax.swing.JLabel jLabelACT11;
    private javax.swing.JLabel jLabelACT12;
    private javax.swing.JLabel jLabelACT13;
    private javax.swing.JLabel jLabelACT14;
    private javax.swing.JLabel jLabelACT15;
    private javax.swing.JLabel jLabelACT16;
    private javax.swing.JLabel jLabelACT17;
    private javax.swing.JLabel jLabelACT18;
    private javax.swing.JLabel jLabelACT19;
    private javax.swing.JLabel jLabelACT2;
    private javax.swing.JLabel jLabelACT20;
    private javax.swing.JLabel jLabelACT21;
    private javax.swing.JLabel jLabelACT22;
    private javax.swing.JLabel jLabelACT23;
    private javax.swing.JLabel jLabelACT24;
    private javax.swing.JLabel jLabelACT25;
    private javax.swing.JLabel jLabelACT3;
    private javax.swing.JLabel jLabelACT4;
    private javax.swing.JLabel jLabelACT5;
    private javax.swing.JLabel jLabelACT6;
    private javax.swing.JLabel jLabelACT7;
    private javax.swing.JLabel jLabelACT8;
    private javax.swing.JLabel jLabelACT9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JTextField jTextFielduserName;
    private javax.swing.JTextField jTextFielduserName10;
    private javax.swing.JTextField jTextFielduserName11;
    private javax.swing.JTextField jTextFielduserName12;
    private javax.swing.JTextField jTextFielduserName13;
    private javax.swing.JTextField jTextFielduserName14;
    private javax.swing.JTextField jTextFielduserName15;
    private javax.swing.JTextField jTextFielduserName16;
    private javax.swing.JTextField jTextFielduserName17;
    private javax.swing.JTextField jTextFielduserName18;
    private javax.swing.JTextField jTextFielduserName19;
    private javax.swing.JTextField jTextFielduserName2;
    private javax.swing.JTextField jTextFielduserName20;
    private javax.swing.JTextField jTextFielduserName21;
    private javax.swing.JTextField jTextFielduserName22;
    private javax.swing.JTextField jTextFielduserName23;
    private javax.swing.JTextField jTextFielduserName3;
    private javax.swing.JTextField jTextFielduserName4;
    private javax.swing.JTextField jTextFielduserName5;
    private javax.swing.JTextField jTextFielduserName6;
    private javax.swing.JTextField jTextFielduserName8;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
